-- Scoring v1 seed data for smoke checks.
-- Requires sql/040_scoring_v1.sql to be applied before running this script.
-- Safe to re-run: upsert by visitor_id.

insert into stg_metrica_visitors_features (
    visitor_id,
    session_id,
    first_seen_at,
    last_seen_at,
    sessions_count,
    total_time_sec,
    pageviews,
    visited_price_page,
    visited_program_page,
    visited_booking_page,
    clicked_booking_button,
    scroll_70,
    return_visitor,
    traffic_source,
    utm_source,
    utm_medium,
    device_type,
    is_bounce,
    source_table,
    loaded_at,
    updated_at
)
values
(
    'scoring_v1_seed_hot_booking_returning',
    'seed_session_001',
    now() - interval '12 day',
    now() - interval '1 day',
    4,
    620,
    12,
    true,
    true,
    true,
    true,
    true,
    true,
    'seed_hot_direct',
    'yandex',
    'cpc',
    'desktop',
    false,
    'seed_scoring_v1',
    now(),
    now()
),
(
    'scoring_v1_seed_warm_content',
    'seed_session_002',
    now() - interval '8 day',
    now() - interval '2 day',
    2,
    160,
    5,
    true,
    true,
    false,
    false,
    true,
    false,
    'seed_warm_organic',
    'google',
    'organic',
    'mobile',
    false,
    'seed_scoring_v1',
    now(),
    now()
),
(
    'scoring_v1_seed_warm_returning',
    'seed_session_003',
    now() - interval '9 day',
    now() - interval '1 day',
    3,
    210,
    6,
    false,
    true,
    false,
    false,
    true,
    true,
    'seed_warm_brand',
    'yandex',
    'brand',
    'desktop',
    false,
    'seed_scoring_v1',
    now(),
    now()
),
(
    'scoring_v1_seed_cold_referral',
    'seed_session_004',
    now() - interval '5 day',
    now() - interval '1 day',
    1,
    90,
    3,
    true,
    false,
    false,
    false,
    true,
    false,
    'seed_cold_referral',
    'blog',
    'referral',
    'mobile',
    true,
    'seed_scoring_v1',
    now(),
    now()
),
(
    'scoring_v1_seed_cold_social',
    'seed_session_005',
    now() - interval '4 day',
    now() - interval '1 day',
    1,
    40,
    1,
    false,
    false,
    false,
    false,
    false,
    false,
    'seed_cold_social',
    'telegram',
    'social',
    'mobile',
    true,
    'seed_scoring_v1',
    now(),
    now()
)
on conflict (visitor_id)
do update set
    session_id = excluded.session_id,
    first_seen_at = excluded.first_seen_at,
    last_seen_at = excluded.last_seen_at,
    sessions_count = excluded.sessions_count,
    total_time_sec = excluded.total_time_sec,
    pageviews = excluded.pageviews,
    visited_price_page = excluded.visited_price_page,
    visited_program_page = excluded.visited_program_page,
    visited_booking_page = excluded.visited_booking_page,
    clicked_booking_button = excluded.clicked_booking_button,
    scroll_70 = excluded.scroll_70,
    return_visitor = excluded.return_visitor,
    traffic_source = excluded.traffic_source,
    utm_source = excluded.utm_source,
    utm_medium = excluded.utm_medium,
    device_type = excluded.device_type,
    is_bounce = excluded.is_bounce,
    source_table = excluded.source_table,
    updated_at = now();
